Make some fixes
paoloap/zaread pull request #23
Opened 2023-10-07 19:28 UTC by iv4n-t3a

Fix invalid `$ZA_CACHE_DIR` with `//` in path

Replace `/bin/sh` to `/bin/bash` becouse this not work when `/bin/sh` isn't link to `/bin/bash`

Fix invalid `md2pdf` usage (it doesn't require -o flag)

2023-10-09 10:49 UTC, iuliandita requested changes
The script was converted to be fully POSIX compliant a [while back](https://github.com/paoloap/zaread/pull/10), the shebang should remain `#!/bin/sh`.
EDIT: it appears that in time it diverged again. There is a larger [pull request](https://github.com/paoloap/zaread/pull/19) that should fix all the POSIX stuff, but it's a bit tricky to merge.

2023-10-09 10:57 UTC, iuliandita requested changes
Also, regarding `-o` for `m2dpdf`, it is not required, indeed, but if you omit it, it defaults to `<md_file>.pdf`.

2023-10-09 18:57 UTC, iv4n-t3a commented
When I run `md2pdf` i see following message and there isn't anything about `-o` flag. Are we using different `md2pdf`?
    md2pdf - Markdown to PDF conversion tool.

    Usage: md2pdf [options] INPUT.MD OUTPUT.PDF

    Options:
        --css=STYLE.CSS

2023-10-09 19:09 UTC, iv4n-t3a commented
But there isn't `-o` option in `md2pdf`. When I run `md2pdf --help` I see following message. Is there another `md2pdf`? I am using [this](https://github.com/jmaupetit/md2pdf). If it is true you should write something in `README.md` about it.

    md2pdf - Markdown to PDF conversion tool.

    Usage: md2pdf [options] INPUT.MD OUTPUT.PDF

    Options:
        --css=STYLE.CSS

2023-10-09 19:09 UTC, iv4n-t3a commented
Also what do you want me to do with `pull request`? Should I close it or what should I change?

2023-10-14 07:54 UTC, closed without merging

2023-10-24 15:14 UTC, aless3 commented
I'm in wsl with ubuntu and if I run ```md2pdf file.md file.pdf``` the conversion has no problems, but if I run ```md2pdf file.md -o file_o.pdf```  the output is ```Usage: md2pdf [options] INPUT.MD OUTPUT.PDF``` and no file ```file_o.pdf``` appears, I think the ```-o``` flag is not only not needed, but it also breaks the md2pdf functionality.
not a big change, maybe a smaller separate pr is better, but I think it would be useful.

2023-10-24 16:02 UTC, iuliandita commented
I'm on linux (arch), and for me, it's the opposite. If I do `md2pdf file.md file.pdf` I get `Usage: md2pdf [OPTIONS] MD_FILE. Error: Got unexpected extra argument (file.pdf)`. Using the `-o`, I get the expected result. I am using `aur/md2pdf-git`, version 0.0.5, which comes from https://github.com/walwe/md2pdf. What version are you running on WSL? How did you install it? It looks like there are different versions...

EDIT: I found [this version](https://github.com/jmaupetit/md2pdf), which looks like it has the options you mentioned. If this is the case, we might need to figure out a way to differentiate between the two.

2023-10-24 16:03 UTC, iuliandita commented
> Also what do you want me to do with `pull request`? Should I close it or what should I change?

I think you can close this PR. The first couple of changes have been made already, we just need to figure out the different variants of `md2pdf`.

2023-10-24 23:32 UTC, aless3 commented
OH.
you are completely right, I use the md2pdf on pip. I didn't even find the other one ahaha (I remember the same error on Linux too, but I have no installation available atm and could not test, but it was the pip package so I suppose that is the source of this "problem") 
honestly I don't even know how we would differentiate them?
but then maybe simply add a settable flag like the other command options and let each user decide? maybe printing an error saying to try to change the flag if something isn't working?
honestly I don't know how feasible (or even easily manteinable) this would, but to me it seems the most simple solution, and also an effective one?
just proponing things tho.